name: Run Python Scripts

# This runs every 30 minutes
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Restore cached database
      uses: actions/cache@v3
      with:
        path: sent_articles.db
        key: db-cache-${{ github.ref }}

    - name: Run Securityboulevard script
      run: python Securityboulevard.py

    - name: Run csoonline script
      run: python csoonline.py

    - name: Run cybernews script
      run: python cybernews.py

    - name: Run helpnetsecurity script
      run: python helpnetsecurity.py

    - name: Run securityweek script
      run: python securityweek.py

    - name: Run thehackernews script
      run: python thehackernews.py

    - name: Run cybernew script
      run: python cybernew.py

    - name: Save updated database to cache
      uses: actions/cache@v3
      with:
        path: sent_articles.db
        key: db-cache-${{ github.ref }}
